
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js/dist/module';
import type { Database } from './types';

const SUPABASE_URL = "https://vtkjlrftizocaqhbsyts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0a2pscmZ0aXpvY2FxaGJzeXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjY2NzYsImV4cCI6MjA1NTgwMjY3Nn0.Gkl1fkmCV9XxmwoDjczKhzq-1q2pRt1Z8u8xRDqJFEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: {
      getItem: (key: string) => {
        try {
          const item = localStorage.getItem(key);
          return item;
        } catch {
          return null;
        }
      },
      setItem: (key: string, value: string) => {
        try {
          localStorage.setItem(key, value);
        } catch {
          // Handle storage errors silently
        }
      },
      removeItem: (key: string) => {
        try {
          localStorage.removeItem(key);
        } catch {
          // Handle storage errors silently
        }
      },
    },
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'X-Client-Info': 'sourlist-app'
    }
  }
});

// Enhanced error handler for better security logging
export const handleSupabaseError = (error: any, context: string) => {
  console.error(`Supabase error in ${context}:`, error);
  
  // Don't expose sensitive error details to users
  if (error?.message?.includes('Row Level Security')) {
    return new Error('Access denied. Please check your permissions.');
  }
  
  if (error?.message?.includes('violates')) {
    return new Error('Invalid data provided. Please check your input.');
  }
  
  return error;
};
