// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtkjlrftizocaqhbsyts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0a2pscmZ0aXpvY2FxaGJzeXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjY2NzYsImV4cCI6MjA1NTgwMjY3Nn0.Gkl1fkmCV9XxmwoDjczKhzq-1q2pRt1Z8u8xRDqJFEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);